# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20161013_1446'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='career',
        ),
    ]
